### ISSUE TITLE
CUDA error from torchpack while saving models

### ISSUE THREAD

**Issue by sandeepnmenon** [zhijian-liu/torchpack#22] opened 2021-10-07 07:05 UTC
While running training using torckpack
`torchpack dist-run -np 2 python train.py configs/spvcnn/cr0p64.yaml --run-dir runs/static_model`

**Environment details**
Package | Version
|-----|------|
Torchpack| 0.3.0
Pytorch | 1.7.0
Torchsparse | 1.1.0
Cuda | 10.0

Getting an error while saving the model using the Saver callback. The error is thrown from the torchpack/distributed/comm.py file as mentioned in the traceback.
<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main()
  File "train.py", line 136, in main
    Saver(max_to_keep=10),
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/train/trainer.py", line 39, in train_with_defaults
    callbacks=callbacks)
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/train/trainer.py", line 88, in train
    self.trigger_epoch()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/train/trainer.py", line 156, in trigger_epoch
    self.callbacks.trigger_epoch()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 90, in trigger_epoch
    self._trigger_epoch()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 308, in _trigger_epoch
    callback.trigger_epoch()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 90, in trigger_epoch
    self._trigger_epoch()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/callbacks/inference.py", line 29, in _trigger_epoch
    self._trigger()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/callbacks/inference.py", line 41, in _trigger
    self.callbacks.after_epoch()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 80, in after_epoch
    self._after_epoch()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 304, in _after_epoch
    callback.after_epoch()
  File "/home/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 80, in after_epoch
    self._after_epoch()
  File "/home/SandeepMenon/e3d_pcd/spvnas/core/callbacks.py", line 54, in _after_epoch
    self.total_seen[i] = dist.allreduce(self.total_seen[i], reduction='sum')
  File "/home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/distributed/comm.py", line 13, in allreduce
    data = allgather(data)
  File "/home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/distributed/comm.py", line 32, in allgather
    sizes = [int(size.item()) for size in sizes]
  File "/home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torchpack/distributed/comm.py", line 32, in <listcomp>
    sizes = [int(size.item()) for size in sizes]
RuntimeError: CUDA error: the launch timed out and was terminated
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: the launch timed out and was terminated
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f40abc888b2 in /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f40b5f7d952 in /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f40abc73b7d in /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5fec3a (0x7f40b6bb4c3a in /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x5fece6 (0x7f40b6bb4ce6 in /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: python() [0x54edf6]
frame #6: python() [0x588fd8]
frame #7: python() [0x5add78]
frame #8: python() [0x5add8e]
frame #9: python() [0x5add8e]
frame #10: python() [0x5add8e]
frame #11: python() [0x5add8e]
frame #12: python() [0x5add8e]
frame #13: python() [0x5add8e]
frame #14: python() [0x5add8e]
frame #15: python() [0x5add8e]
frame #16: python() [0x5add8e]
frame #17: python() [0x5add8e]
frame #18: python() [0x5add8e]
frame #19: python() [0x5add8e]
frame #20: python() [0x5add8e]
frame #21: python() [0x5add8e]
frame #22: python() [0x5add8e]
frame #23: python() [0x56b606]
<omitting python frames>
frame #29: __libc_start_main + 0xe7 (0x7f40bc6c1bf7 in /lib/x86_64-linux-gnu/libc.so.6)

[deepen-Z11PA-U12-Series:24283] *** Process received signal ***
[deepen-Z11PA-U12-Series:24283] Signal: Aborted (6)
[deepen-Z11PA-U12-Series:24283] Signal code:  (-6)
[deepen-Z11PA-U12-Series:24283] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3f040)[0x7f40bc6df040]
[deepen-Z11PA-U12-Series:24283] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f40bc6defb7]
[deepen-Z11PA-U12-Series:24283] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f40bc6e0921]
[deepen-Z11PA-U12-Series:24283] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c957)[0x7f40b7b42957]
[deepen-Z11PA-U12-Series:24283] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92ae6)[0x7f40b7b48ae6]
[deepen-Z11PA-U12-Series:24283] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x91b49)[0x7f40b7b47b49]
[deepen-Z11PA-U12-Series:24283] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x2a8)[0x7f40b7b484b8]
[deepen-Z11PA-U12-Series:24283] [ 7] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x10573)[0x7f40b78ae573]
[deepen-Z11PA-U12-Series:24283] [ 8] /lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Resume+0x125)[0x7f40b78aedf5]
[deepen-Z11PA-U12-Series:24283] [ 9] /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libc10_cuda.so(_ZN3c104cuda20CUDACachingAllocator10raw_deleteEPv+0x9e9)[0x7f40b5f7d869]
[deepen-Z11PA-U12-Series:24283] [10] /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libc10.so(_ZN3c1010TensorImpl17release_resourcesEv+0x4d)[0x7f40abc73b7d]
[deepen-Z11PA-U12-Series:24283] [11] /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libtorch_python.so(+0x5fec3a)[0x7f40b6bb4c3a]
[deepen-Z11PA-U12-Series:24283] [12] /home/deepen/SandeepMenon/venv-e3d/lib/python3.6/site-packages/torch/lib/libtorch_python.so(+0x5fece6)[0x7f40b6bb4ce6]
[deepen-Z11PA-U12-Series:24283] [13] python[0x54edf6]
[deepen-Z11PA-U12-Series:24283] [14] python[0x588fd8]
[deepen-Z11PA-U12-Series:24283] [15] python[0x5add78]
[deepen-Z11PA-U12-Series:24283] [16] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [17] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [18] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [19] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [20] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [21] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [22] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [23] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [24] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [25] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [26] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [27] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [28] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] [29] python[0x5add8e]
[deepen-Z11PA-U12-Series:24283] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[63105,1],1]
  Exit code:    134

```
</details>

**Comment by zhijian-liu** [comment] 2021-12-27 15:56
@sandeepnmenon, I'm checking in to see whether the issue is still there after upgrading CUDA and PyTorch.

**Comment by sandeepnmenon** [comment] 2021-12-28 07:38
I am able to repro this while running  on V100 VM. 
However, when I tried the same environment setup on a 1080Ti, I am not able to repro the issue.

**Comment by zhijian-liu** [comment] 2021-12-28 21:57
Thanks for the update! As this seems to be related to PyTorch and CUDNN (see https://github.com/pytorch/pytorch/issues/37449), I'm closing this issue for now.

**Closed by zhijian-liu** 2021-12-28 21:57 UTC
Labels: bug
